### ISSUE TITLE
cat command causes panic.

### ISSUE THREAD

**Issue by markatlnk** [lurk101/pshell#25] opened 2023-02-15 22:23 UTC
Using latest version 1.2.22

File system was created by previous version, it had only 2 small files on it. One was a small C program and the other was a text file. 

Attempting to cat either of those files results in PANIC and dropping out of terminal mode.

Using MacBook Pro (latest OS) screen command.

vi works fine as does the C compiler, haven't tested any other things.

Great program by the way.

**Comment by fdufnews** [comment] 2023-02-16 11:26
I have found the fwrite in cat_cmd() being the cause of the PANIC.
Cannot explain why. Problem with stdout ???
I bypassed this with the following changes, of which I am not really satisfied, but it works. 
```
static void cat_cmd(void) {
    if (check_mount(true))
        return;
    if (check_name())
        return;
    lfs_file_t file;
    if (fs_file_open(&file, full_path(argv[1]), LFS_O_RDONLY) < LFS_ERR_OK) {
        strcpy(result, "error opening file");
        return;
    }
    int l = fs_file_seek(&file, 0, LFS_SEEK_END);
    fs_file_seek(&file, 0, LFS_SEEK_SET);
    char buf[256];
    while (l) {
        int l2 = l;
        if (l2 > sizeof(buf)-1)                                             // <- change here 
            l2 = sizeof(buf)-1;                                             // <- change here 
        if (fs_file_read(&file, buf, l2) != l2) {
            sprintf(result, "error reading file");
            break;
        }
        buf[255]=0;                                                         // <- change here 
        printf(buf);                                                          // <- change here 
//        fwrite(buf, 1, l2, stdout);
        l -= l2;
    }
    fs_file_close(&file);
}
```

**Comment by lurk101** [comment] 2023-02-17 21:35
fixed with https://github.com/lurk101/pshell/commit/857093dfb1b178ec33fbcc995da3b8d3f953ecc6

**Closed by lurk101** 2023-02-17 21:35 UTC
